# CI for command line NodeJS Applications
name: nodejs
on: ['push']

env:
  CI: true
  FORCE_COLOR: 2

jobs:
  run:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: ['12', '14']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: npm install

      - name: Run build
        run: npm run-script build

      - name: Run Test
        run: npm run-script test
